### PR TITLE
Fix track context manager

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
### Changes

Fix `track` usage as a context manager. This is a regression after #2892.

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
@nikita-savelyevv What regression? And why is it not cached by tests?

**Comment by nikita-savelyevv** [comment]
> What regression?

There will be an error if `track` is used as a context manager:
```
Failed: 'Progress' object has no attribute 'progress'
```

> And why is it not cached by tests?

There are no tests for the progress tracker. I've added them now.

**Review by AlexanderDokuchaev — APPROVED** [review]
