### ISSUE TITLE
NNCF Installation Fails with Python 3.12, Blocking Ultralytics YOLO OpenVINO Exports

### ISSUE THREAD

**Issue by glenn-jocher** [openvinotoolkit/nncf#3463]
## Summary
When attempting to install NNCF (>=2.14.0) with Python 3.12, the installation fails due to dependency issues. This is critically affecting our CI pipeline on the Ultralytics repository where we're adding Python 3.12 and 3.13 support. The error occurs during the OpenVINO export tests for YOLO models that depend on NNCF for int8 quantization. These OpenVINO exports are a crucial component of our CI pipeline and are essential for our users who deploy YOLO models to edge devices.

PR with Python 3.12 CI showing error: https://github.com/ultralytics/ultralytics/pull/20366
Action URL showing error: https://github.com/ultralytics/ultralytics/actions/runs/14685205478

## Environment
- Python 3.12.10
- Ubuntu 24.04.2 LTS
- ARM64 architecture (GitHub Actions runner)
- Attempting to install via pip: `pip install nncf>=2.14.0`
- Ultralytics YOLO version 8.3.118

## Error Description
The installation of NNCF fails with the error:
```
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
```

This appears to be happening in a dependency (jstyleson) during the metadata generation phase. The error occurs specifically in setuptools:
```
File "/opt/hostedtoolcache/Python/3.12.10/arm64/lib/python3.12/site-packages/setuptools/_core_metadata.py", line 293, in _distribution_fullname
  canonicalize_version(version, strip_trailing_zero=False),
```

## Steps to Reproduce
1. Use Python 3.12
2. Run `pip install nncf>=2.14.0`
3. Observe the installation failure
4. Try to export a YOLO model to OpenVINO with int8 quantization

## Impact
This issue is blocking our CI pipeline from testing YOLO OpenVINO exports with int8 quantization on Python 3.12. The OpenVINO export tests that require NNCF are failing, which is a critical path for us as many of our users rely on optimized OpenVINO exports for edge deployment. Specifically, 40 OpenVINO export test cases are failing, all related to int8 quantization that relies on NNCF.

Our users depend on the Ultralytics YOLO OpenVINO export functionality for deploying models to Intel hardware, and this issue prevents them from using the latest Python versions with our pipeline. The OpenVINO export is one of our most important deployment targets alongside TensorRT, ONNX, and other formats.

## Additional Information
- This issue only affects Python 3.12 and potentially 3.13. Our YOLO OpenVINO export CI works fine with Python 3.11.
- The issue appears to be with a dependency (jstyleson) that hasn't been updated to be compatible with changes in the packaging/setuptools libraries in Python 3.12.
- The error occurs during the installation of NNCF's dependencies rather than in NNCF itself.
- All non-int8 OpenVINO exports for YOLO models work correctly on Python 3.12, it's only the NNCF-dependent quantized exports that are failing.

## Suggested Solution
Please update the dependency chain to ensure compatibility with Python 3.12, potentially by:
1. Updating jstyleson to use more modern packaging practices
2. Adding Python version constraints in your package metadata
3. Finding alternative dependencies that are Python 3.12 compatible

This would allow us to fully support Ultralytics YOLO OpenVINO exports with int8 quantization on the latest Python versions, which is crucial for our users who deploy on edge devices.

Let me know if you need any additional information or logs to help diagnose this issue.

### Environment

```
Ultralytics 8.3.118 🚀 Python-3.12.10 torch-2.7.0+cpu CPU (Neoverse-N2)
Setup complete ✅ (4 CPUs, 15.6 GB RAM, 27.0/71.6 GB disk)

OS                  Linux-6.8.0-1021-azure-aarch64-with-glibc2.39
Environment         Linux
Python              3.12.10
Install             git
Path                /home/runner/work/ultralytics/ultralytics/ultralytics
RAM                 15.58 GB
Disk                27.0/71.6 GB
CPU                 Neoverse-N2
CPU count           4
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 2.1.1<=2.1.1,>=1.23.0
matplotlib          ✅ 3.10.1>=3.3.0
opencv-python       ✅ 4.11.0.86>=4.6.0
pillow              ✅ 11.2.1>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.15.2>=1.4.1
torch               ✅ 2.7.0+cpu>=1.8.0
torch               ✅ 2.7.0+cpu!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.22.0>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 7.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.14>=2.0.0

RUNNER_OS: Linux
GITHUB_EVENT_NAME: workflow_dispatch
GITHUB_WORKFLOW: Ultralytics CI
GITHUB_ACTOR: UltralyticsAssistant
GITHUB_REPOSITORY: ultralytics/ultralytics
GITHUB_REPOSITORY_OWNER: ultralytics
Using Python 3.12.10 environment at: /opt/hostedtoolcache/Python/3.12.10/arm64
Package                            Version     Editable project location
---------------------------------- ----------- -----------------------------------------
absl-py                            2.2.2
alembic                            1.15.2
annotated-types                    0.7.0
anyio                              4.9.0
astunparse                         1.6.3
attrs                              25.3.0
blinker                            1.9.0
cachetools                         5.5.2
cattrs                             24.1.3
certifi                            2025.4.26
charset-normalizer                 3.4.1
click                              8.1.8
cloudpickle                        3.1.1
contourpy                          1.3.2
coremltools                        8.2
coverage                           7.8.0
cycler                             0.12.1
databricks-sdk                     0.50.0
deprecated                         1.2.18
docker                             7.1.0
fastapi                            0.115.12
filelock                           3.18.0
flask                              3.1.0
flatbuffers                        25.2.10
fonttools                          4.57.0
fsspec                             2025.3.2
gast                               0.6.0
gitdb                              4.0.12
gitpython                          3.1.44
google-auth                        2.39.0
google-pasta                       0.2.0
graphene                           3.4.3
graphql-core                       3.2.6
graphql-relay                      3.2.0
greenlet                           3.2.1
grpcio                             1.71.0
gunicorn                           23.0.0
h11                                0.16.0
h5py                               3.13.0
idna                               3.10
importlib-metadata                 8.6.1
iniconfig                          2.1.0
itsdangerous                       2.2.0
jinja2                             3.1.6
joblib                             1.4.2
keras                              3.9.2
kiwisolver                         1.4.8
libclang                           18.1.1
mako                               1.3.10
markdown                           3.8
markdown-it-py                     3.0.0
markupsafe                         3.0.2
matplotlib                         3.10.1
mdurl                              0.1.2
ml-dtypes                          0.5.1
mlflow                             2.22.0
mlflow-skinny                      2.22.0
mpmath                             1.3.0
namex                              0.0.9
networkx                           3.4.2
numpy                              2.1.1
onnx                               1.[17](https://github.com/ultralytics/ultralytics/actions/runs/14685205478/job/41212923117#step:6:18).0
opencv-python                      4.11.0.86
opentelemetry-api                  1.32.1
opentelemetry-sdk                  1.32.1
opentelemetry-semantic-conventions 0.53b1
openvino                           2025.1.0
openvino-telemetry                 2025.1.0
opt-einsum                         3.4.0
optree                             0.15.0
packaging                          20.9
pandas                             2.2.3
pillow                             11.2.1
pip                                25.1
pluggy                             1.5.0
protobuf                           5.29.4
psutil                             7.0.0
py-cpuinfo                         9.0.0
pyaml                              25.1.0
pyarrow                            19.0.1
pyasn1                             0.6.1
pyasn1-modules                     0.4.2
pycocotools                        2.0.8
pydantic                           2.11.3
pydantic-core                      2.33.1
pygments                           2.19.1
pyparsing                          3.2.3
pytest                             8.3.5
pytest-cov                         6.1.1
python-dateutil                    2.9.0.post0
pytz                               2025.2
pyyaml                             6.0.2
requests                           2.32.3
rich                               14.0.0
rsa                                4.9.1
scikit-learn                       1.6.1
scipy                              1.15.2
seaborn                            0.13.2
setuptools                         79.0.1
six                                1.17.0
smmap                              5.0.2
sniffio                            1.3.1
sqlalchemy                         2.0.40
sqlparse                           0.5.3
starlette                          0.46.2
sympy                              1.13.3
tensorboard                        2.19.0
tensorboard-data-server            0.7.2
tensorflow                         2.19.0
tensorflow-hub                     0.12.0
tensorflowjs                       3.[18](https://github.com/ultralytics/ultralytics/actions/runs/14685205478/job/41212923117#step:6:19).0
tensorstore                        0.1.74
termcolor                          3.0.1
threadpoolctl                      3.6.0
torch                              2.7.0+cpu
torchvision                        0.22.0
tqdm                               4.67.1
typing-extensions                  4.13.2
typing-inspection                  0.4.0
tzdata                             [20](https://github.com/ultralytics/ultralytics/actions/runs/14685205478/job/41212923117#step:6:21)25.2
ultralytics                        8.3.118     /home/runner/work/ultralytics/ultralytics
ultralytics-thop                   2.0.14
urllib3                            2.4.0
uvicorn                            0.34.2
werkzeug                           3.1.3
wheel                              0.45.1
wrapt                              1.17.2
zipp                               3.21
```

### Minimal Reproducible Example

1. Use Python 3.12
2. Run `pip install nncf>=2.14.0`
3. Observe the installation failure
4. Try to export a YOLO model to OpenVINO with int8 quantization

### Are you going to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MaximProshin** [comment]
@glenn-jocher , thanks for reporting it and your detailed description! 
@AlexanderDokuchaev , please investigate it.

**Comment by AlexanderDokuchaev** [comment]
Hi @glenn-jocher 
The problem package is `jstyleson`, that was already removed https://github.com/openvinotoolkit/nncf/pull/3373 on develop branch, but it can be installed correctly before removing deprecated functions of setuptools in 2026, now on installation expected only a warning
```
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2026-Mar-03, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
``` 

Looks like the main reason of the problem that used outdated version `packaging==20.9` that does not contain `strip_trailing_zero` argument for `canonicalize_version` function ( `strip_trailing_zero` was added in 22.0).

In CI of ultralytics

|       | setuptools | packaging | status | 
| :--- | :---: | :---: | :---: |
| windows-latest, 3.12, latest | 79.0.1 | 20.9  | FAIL |
| ubuntu-24.04-arm, 3.12, latestt | 79.0.1 | 20.9 | FAIL | 
| ubuntu-latest, 3.12, latest    | 79.0.1 | 23.2  | PASS |
| macos-14, 3.12, latest          |  79.0.1 | 23.2  | PASS |

Setuptools has no requirements with minimal version of `packaging` by testing with `packaging>=24.2` https://github.com/pypa/setuptools/blob/v79.0.1/pyproject.toml#L43 

So, in next release of NNCF it will be fixed by removing of jstyleson from requirements.
Recommend to check ci environment to find a reason of installation old version of `packaging`, 20.9 is released in 2021.

**Comment by glenn-jocher** [comment]
@AlexanderDokuchaev thanks for investigating! Yes you are right, the older version of `packaging` was causing this. I've updated the Ultralytics package to install `packaging>=23.2` before attempting to install NNCF and now everything works correctly. Updated in https://github.com/ultralytics/ultralytics/pull/20366.

Closing PR!
